/*
 *
 *
 * Executable generator. The task of this code is to take the assembly
 * generated by the code generator and transform it into an executable file.
 *
 */

#ifndef XGEN_H
#define XGEN_H

/*
 * Generates an executable file from a string containing assembly code.
 *
 * filename: the source file name.
 * assemblyCode: the string containing the assembly code.
 * outputName: the name of the output file.
 *
 */
void generateExec(char* filename, char* assemblyCode, char* outputName);

#endif

